databases:
  - name: my_db_one
    ipAllowList: []
    databaseName: my_rails_app_one_prod_db
    user: my_rails_app_one_prod_db
    plan: basic-256mb

services:
  - type: web
    name: my_rails_app_one
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_db_one
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  